README.md
Thanks for the great library, I used it to create a demo website to showcase how you can build a Visual Search engine using MXNet and HNSW: https://thomasdelteil.github.io/VisualSearch_MXNet/
I was thinking it could be a good idea to add a demo section in order to point to the website to provide other users with ideas and maybe inspiration. It would be great to also see how other users are using this library if there are any other demos out there.
If such a section is not appropriate feel free to close the PR, I really won't be offended 😄
=> [suggestion] Adding a demo section

hnswlib/visited_list_pool.h
Trivial patch to fix valgrind warning about mismatched delete / new.
Details of warning previously seen:
```
==16753== Mismatched free() / delete / delete []
==16753==    at 0x4C2D2DB: operator delete(void*) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==16753==    by 0x10B1B0: hnswlib::VisitedList::~VisitedList() (in /«rootdir»/hnsw_test)
==16753==    by 0x10B456: hnswlib::VisitedListPool::~VisitedListPool() (in /«rootdir»/hnsw_test)
==16753==    by 0x10BE9C: hnswlib::HierarchicalNSW<float>::~HierarchicalNSW() (in /«rootdir»/hnsw_test)
==16753==    by 0x10BEF9: hnswlib::HierarchicalNSW<float>::~HierarchicalNSW() (in /«rootdir»/hnsw_test)
==16753==    by 0x10ACE7: main (in /«rootdir»/hnsw_test)
==16753==  Address 0x5bde1e0 is 0 bytes inside a block of size 20,000 alloc'd …
```
=> hnswlib/visited_list_pool.h: use delete[] to match new[]

hnswlib/hnswalg.h
This prevents an `Invalid read of size 4` in the `searchBaseLayer`
(hnswalg.h:194).
=> hnswlib/hnswalg.h: increase linked list element size by 1

hnswlib/hnswalg.h, hnswlib/hnswlib.h
This is a trivial change to enable users to instantiate a const object and still be able to call searchKnn.
=> Add some const qualifiers to enable usage of searchKnn in const contexts

hnswlib/space_ip.h, hnswlib/space_l2.h
A fix for the trivial issue #67. Recent changes to the [R devtools package](https://cran.r-project.org/package=devtools) defaults causes these warnings to appear when building [R bindings](https://github.com/jlmelville/rcpphnsw) to hnsw.
=> Remove unnecessary semi-colons

hnswlib/bruteforce.h
Accommodates changes made in 4beb352cf8187b948c079029df8f8d4ac8bba445
=> Fix missing const qualifiers in searchKnn in BruteForceSearch

hnswlib/hnswalg.h, python_bindings/tests/bindings_test_getdata.py
If you query `getDataByLabel` for a label that's not in the index, it will return a vector with un-initialized data. I believe, because of the way `std::unordered_map`'s `[]` operator works, it will also add that random vector to the map.
This change instead returns the data when that label exists, and otherwise throws an error.
I also added another Python test to verify this behavior.
=> Raising an error when trying to get data for a non-existent label

hnswlib/hnswalg.h, hnswlib/hnswlib.h, hnswlib/space_ip.h, hnswlib/space_l2.h
In order to submit the [R bindings for HNSW](https://github.com/jlmelville/rcpphnsw) to CRAN, it is a requirement that C++ code build without needing non-portable flags like `-march=native`. @LTLA and I have made those changes and we were wondering if this might also be useful for those hoping to use HNSW on architectures without AVX, SSE and the like. Hence this PR.
Changes in roughly decreasing order of importance:
* Added a preprocessor token`NO_MANUAL_VECTORIZATION`. If defined (e.g. by using `-DNO_MANUAL_VECTORIZATION` in the compiler flags), then you don't need to specify `-march=native`  and AVX and SSE will not be used. If you don't define `NO_MANUAL_VECTORIZATION` then the code will build as before, i.e. anyone who doesn't care about this should be unaffected.
* There are some …
=> Add preprocessor directives for non-portable code.

hnswlib/hnswalg.h
There was a multi-threaded bug introduced by adding support for element deletions - deleted flag was stored in the same variable as the link list size without additional locks. The same lock as for linked list cannot be used due to possible deadlocks so to solve the problem they are now stored in different variables. 
To make it backward compatible with respect to saved indices the 4-byte int is now divide into 2 short ints (2-bytes) - one for the link list size, one for the delete flag. A lock is added to update the element (e.g. autodelete).
However, a call to delete operation is still non-thread safe.  It can be solved right now by using a different set of locks, but they are rather memory expensive. So probably deletions should be locked externally.
The 1B SIFT test exposed the bug …
=> Fix delete

hnswlib/hnswalg.h
howdy again,
here is a simple patch to avoid warnings on systems where sizeof(size_t) != sizeof(int).
cheers, piem
=> use size_t counters to avoid size_t to int comparisons

hnswlib/hnswalg.h
howdy,
This patch fixes the prototype of `setExternalLabel`, which has no return value.
cheers, piem
=> setExternalLabel returns void

hnswlib/bruteforce.h, hnswlib/hnswalg.h
Throw runtime_error when malloc fails
=> Throw exception on malloc fails

hnswlib/space_ip.h, hnswlib/space_l2.h
Currently SIMD (SSE or AVX) is used for the cases when dimension is
multiple of 4 or 16, while when dimension size is not strictly equal
to multiple of 4 or 16 a slower non-vectorized method is used.
To improve performnance for these cases new methods are added:
`L2SqrSIMD(4|16)ExtResidual` - it relies on existing `L2SqrSIMD(4|16)Ext`
to compute up to *4 and *16 dimensions and finishes residual
computation by non-vectorized method `L2Sqr`.
=> Perf improvement for dimension not of factor 4 and 16

CMakeLists.txt, README.md, examples/update_gen_data.py, examples/updates_test.cpp, hnswlib/hnswalg.h, hnswlib/hnswlib.h
1) Add support for performing efficient updates of existing feature vectors for elements by modifying the graph.
2) Add fix for finding out the right entry point while performing element insertions.
=> Algorithm to perform dynamic/incremental updates of feature vectors

hnswlib/hnswalg.h
Adding cassert include in header to fix compilation error on Ubuntu 18.04 with g++ 7.3.0. Fixes an issue reported by author in #229
=> Adding cassert include in header to fix Bionic/gcc730 compilation

hnswlib/hnswalg.h
In order to compile with -Werror=sign_compare and -Werror=reorder, a few small int -> size_t replacements and constructor initialization list.
=> GCC sign_compare and reorder warning flags patches

README.md, hnswlib/hnswalg.h, python_bindings/bindings.cpp, python_bindings/tests/bindings_test_pickle.py
* [Index](https://github.com/dbespalov/hnswlib/blob/python_bindings_pickle_io/python_bindings/bindings.cpp) class
* Static factory methods `createFromIndex` and `createFromParams` for Index construction from another Index object or Index parameter tuple, respectively
* Method `getIndexParams` serializes Index object. Returns a tuple with Index parameters.
* Method `getAnnData` returns a tuple with hnsw-specific parameters. Copy of `appr_alg->data_level0_memory_` and `appr_alg->linkLists_` are returned as `py::array_t<char>` objects to avoid additional copying from python side
* Python bindings for [Index](https://github.com/dbespalov/hnswlib/blob/python_bindings_pickle_io/python_bindings/bindings.cpp) class 
* Index serialization is implemented with `py::pickle` definition from pybind11
* …
=> Add pickle support to python bindings `Index` class

python_bindings/bindings.cpp
@yurymalkov @dyashuni this PR is still a WIP and untested. I should be a able to finish it tomorrow
=> Use dict for Index serialization

hnswlib/hnswalg.h
fix #115 `currObj` shuld be updated as the nearest node in `topCandidates`
=> currObj should be updated as the closest from all candidated.

CMakeLists.txt, examples/searchKnnCloserFirst_test.cpp, hnswlib/bruteforce.h, hnswlib/hnswalg.h, hnswlib/hnswlib.h
In issue #146, i add a templae interface 
https://github.com/nmslib/hnswlib/blob/3c6a84fb54a2a92dc4b7dc3e13dbae3d99892444/hnswlib/hnswlib.h#L74-L76
But it cannot be overrided. So I removed the template and make it a virtual function.
=> Remove temlate interface searchKnn

README.md
This is just a suggestion of doc improvement.
I have made description of `labels` and `data_labels` together since...
1. There's no argument called `labels` for `add_items` func.
2. It felt like `labels` were a typo of `data_labels` from a previous [commit](https://github.com/nmslib/hnswlib/commit/5c20009894603810f1a3c3135e4bdf5d4025a782#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R37).
=> Improved description of `add_items`

python_bindings/bindings.cpp
Currently, `hnswlib` will segfault if called from Python with an unrecognized `space_name`, as `l2space` is left undefined. This PR proposes a fix for that by throwing an exception instead.
=> Throw an exception if passed an unrecognized space_name.

hnswlib/hnswlib.h, hnswlib/space_ip.h, hnswlib/space_l2.h
Add AVX512 support to L2 and IP algorithms. 
Testing with Ann-Benchmarks shows measurable improvement on c5.4xlarge and m6i.4xlarge instances. 
c5.4xlarge results
fashion-mnist-784-euclidean
mnist-784-euclidean
nytimes-256-angular
sift-128-euclidean
m6i.4xlarge results: 
fashion-mnist-784-euclidean
mnist-784-euclidean
nytimes-256-angular
sift-128-euclidean
=> Added AVX512 support for space_l2 and space_ip.

CMakeLists.txt, hnswlib/hnswalg.h, hnswlib/visited_list_pool.h
This allows other CMake projects to include HNSW via CMake's `FetchContent` approach, e.g.,
```
FetchContent_Declare(
hnswlib
GIT_REPOSITORY https://github.com/nmslib/hnswlib
GIT_TAG master
)
FetchContent_MakeAvailable(hnswlib)
target_link_libraries(my_lib PUBLIC hnswlib)
```
A real-world example is available at https://github.com/LTLA/knncolle/blob/master/extern/CMakeLists.txt.
I moved the test building directives into a conditional that only triggers when actually building Hnswlib. This ensures that downstream projects are not saddled with the need to build the tests when all they want are the headers.
I also took the liberty of making `getDataByLabel` `const`, to indicate that it could be safely used in parallel frameworks that do not expect modifications to the index upon query; and I …
=> Expose CMake target for use via FetchContent

hnswlib/hnswalg.h
In the case of marked_deleted, Insufficient results may occur(edge case)
* If top_candidate is insufficient, additional search is performed for the Candidate_set.
* When the experiment was conducted with 50% of deletion masking, about 3 out of 10,000 cases had insufficient results. (eg. 100 nodes have been requested, but 1 is returned.)
* If all of the neighbors of the entry point are deleted nodes, the candidate_set contains data to be searched, but the lower_bound is not modified by the top_candidate, so there is a problem of stopping without further searching.
[Examples of cases that occurrence]
<details>
e.g Entry point is a normal node. 
If all neighboring entries at the entry point are masked deletion nodes, the Candidate_set tour ends at the lower_bound.
e.g If there were no delete …
=> Insufficient results may occur(has marked_deleted node)

hnswlib/hnswlib.h, hnswlib/space_ip.h, hnswlib/space_l2.h, setup.py
Regarding issue https://github.com/nmslib/hnswlib/issues/292
AVX runtime check: I've made a wrapper function for the simd functions and runtime check which to use.  Not the cleanest implementation but I think of a simpler way.
In addition, for issue https://github.com/conda-forge/hnswlib-feedstock/pull/11
I've tested building on one machine and installing in another with different AVX capabilities with both conda and pip.  The '-march=native' in setup.py is a factor in illegal instruction errors.  Taking it out solves this issue.  So I propose a environment flag 'HNSWLIB_NO_NATIVE', which is checked for in setup.py.  This will allow conda build recipes to choose not to use '-march=native'.
=> AVX runtime check

setup.py
I failed to install hnswlib with pip on Apple M1. The output error message is as follows:
```sh
$ pip install hnswlib
Collecting hnswlib
Using cached hnswlib-0.6.0.tar.gz (30 kB)
...
Building wheels for collected packages: hnswlib
Building wheel for hnswlib (pyproject.toml) ... error
ERROR: Command errored out with exit status 1:
...
clang: error: the clang compiler does not support '-march=native'
error: command '/usr/bin/clang' failed with exit code 1
----------------------------------------
ERROR: Failed building wheel for hnswlib
Failed to build hnswlib
ERROR: Could not build wheels for hnswlib, which is required to install pyproject.toml-based projects
$
```
The cause of this error is that Apple M1's clang does not support the `march=native` option.  I have fixed setup.py so that the …
=> Disable march=native option when building on Apple M1

python_bindings/bindings.cpp
Overflow caused by using uint32 in pointer operation. Large indexes are not saved properly.
commit changes uint32->uint64 and now the test is passing.
Thanks to Kai Wohlfahrt (https://www.linkedin.com/in/kwohlfahrt/ ) for reporting
Script to reproduce 
```python
import pickle
import numpy as np
import hnswlib
n = 5_000_000
d = 400
data=np.float32(np.random.random((n, 4)))
data=np.pad(data, ((0,0), (0, d-4)))
print(data.shape)
ann = hnswlib.Index("l2", d)
ann.init_index(n, ef_construction=10, M=16)
ann.add_items(data)
total_elements_to_test=n
print("testing recall")
labels, _ = ann.knn_query(data[:total_elements_to_test], k = 1)
print("recall:",np.sum(labels.reshape(-1)==np.arange(0,total_elements_to_test))/total_elements_to_test)
pickled=pickle.dumps(ann)
ann=pickle.loads(pickled) …
```
=> Fix a bug in large pickles

hnswlib/space_ip.h
Fixing a bug causing IP functions in some optimizations and cases to round up the calculated result.
when using `InnerProductSIMD16ExtResiduals` or `InnerProductSIMD4ExtResiduals`, we call `InnerProductSIMD16Ext` or `InnerProductSIMD4Ext` respectively, and then also calling `InnerProduct`. each result already calculated `1.0f - {IP}` so we need to sum them and then subtract one 1.0f back to get `1.0f - {IP16/4 + IPrest}` and not `2.0f - {IP16/4 + IPrest}`.
When comparing close vectors, this can lead to losing the actual IP and rounding up the result, and getting inconsistent results in different optimizations.
=> IP space roundup bug fix

hnswlib/bruteforce.h, python_bindings/bindings.cpp
This pull request fixes exception throwing. For example, this pull request changes make the error messages appropriate.
Currently release version:
```python
>>> import hnswlib
>>> p = hnswlib.Index(space='foo', dim=8)
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
RuntimeError: Caught an unknown exception!
>>> p = hnswlib.Index(space='l2', dim=8)
>>> p.init_index(max_elements=8)
>>> p.init_index(max_elements=8)
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
RuntimeError: Caught an unknown exception!
>>>
```
Applying this pull request changes:
```python
>>> import hnswlib
>>> p = hnswlib.Index(space='foo', dim=8)
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
RuntimeError: Space name must be one of l2, ip, or cosine. …
```
=> Fix exception throwing

hnswlib/hnswlib.h, hnswlib/space_ip.h, hnswlib/space_l2.h
Greetings!
First of all, thank you for your library, it's awesome and useful. 
But here's a tiny fix I dare to propose: as soon some of the headers contain definitions without `static` specified, could you add it to them?
Currenlty those definitions have global linkage, which means that in certain cases someone is likely to get "multiple definitions" error, I can provide you a MCVE of that here or in a separate issue if you like.
The fix is small and should not affect performance, tests pass fine.
@yurymalkov , what'd you say?
=> Fix global linkages

README.md
a trivial fix to the `README.md` where the final quote on the python test invocation was missing.
=> add missing quote on README

hnswlib/bruteforce.h, hnswlib/hnswalg.h
Fixes #393.
Testing: I ran `make test` and got no different results between the output in this PR and the current state of `develop`. That said I do see these warnings in the output (these are *also* present in `develop`):
```
.Adding all elements (10000)
.Running pickle tests for <hnswlib.Index(space='cosine', dim=32)>
.Running pickle tests for <hnswlib.Index(space='ip', dim=16)>
Warning: 1 labels are missing from ann results (k=25, err_thresh=5)
Warning: 1 labels are missing from ann results (k=25, err_thresh=5)
Warning: 1 labels are missing from ann results (k=25, err_thresh=5)
Warning: 1 ann distance values are different from brute-force values (total # of values=2500, dists_thresh=50)
Warning: 1 labels are missing from ann results (k=25, err_thresh=5)
Warning: 1 labels are missing …
```
=> initialize fields in constructor

README.md
A beautiful Rust implementation. I have run benchmarks for various dataset with very good performance and recall. More metric distance are supported including hamming, Hellinger distance, Jensen-Shannon distance between probability distributions (f32 and f64).  There is  A Trait to enable the user to implement its own distances. It takes as data slices of types T satisfying T:Serialize+Clone+Send+Sync.
=> Add rust implementation

.github/workflows/build.yml, CMakeLists.txt, examples/searchKnnWithFilter_test.cpp, hnswlib/bruteforce.h, hnswlib/hnswalg.h, hnswlib/hnswlib.h
Fixes https://github.com/nmslib/hnswlib/issues/366
**Summary of the change**
An optional filtering function can be specified as a template parameter that determines if a given ID should be picked. The default is a function that allows all labels via a`return true` -- this will be optimised away by the compiler, so there will be no extra cost for those who don't provide a filtering function. 
The use of a templated filter function also ensures that the filtering logic can be entirely inlined by the compiler, and is an implementation detail, instead of forcing a `std::set<>` of allowed IDs as discussed in #366.
I've added a test that asserts on both the brute force and hnsw implementations. Verified that existing search knn tests pass.
=> Filter elements with an optional filtering function

hnswlib/hnswlib.h
See discussion at #405:
MSVC compilers do not define `__SSE__`, but indicate SSE usage slightly differently. That's why I think the problem with including `#include "cpu_x86.h"` never showed up in build tests.
=> Set USE_SSE with msvc compilers and fix unknown header inclusion

.gitignore, examples/searchKnnCloserFirst_test.cpp, examples/searchKnnWithFilter_test.cpp, examples/updates_test.cpp, hnswlib/bruteforce.h, hnswlib/hnswalg.h, hnswlib/hnswlib.h, hnswlib/space_ip.h, hnswlib/space_l2.h, hnswlib/visited_list_pool.h, main.cpp, python_bindings/bindings.cpp, sift_1b.cpp, sift_test.cpp
Added a new method to replace the deleted elements and tests
Refactoring:
- deleted unused function searchKnnInternal
- improved code readability
Edit:
I left only refactoring
=> Refactoring

python_bindings/bindings.cpp
Introduced new functions `get_input_array_shapes` and `get_input_ids_and_check_shapes` to remove code duplication
Small refactoring: added spaces
=> Remove some code duplication in bindings

.github/workflows/build.yml, python_bindings/tests/bindings_test_recall.py
Added -v to python unittest discovery to get nicely looking logs in actions (we can see the test names and results):
```
testRandomSelf (bindings_test.RandomSelfTestCase) ... ok
testGettingItems (bindings_test_getdata.RandomSelfTestCase) ... ok
...
```
Update tests in bindings_test_recall.py. Previously the tests almost always passed because there were no checks for recall values. I added a threshold to check that recall is high enough and doesn't change after index serialization.
=> Update python recall test

examples/searchKnnWithFilter_test.cpp, hnswlib/bruteforce.h, hnswlib/hnswalg.h, hnswlib/hnswlib.h, python_bindings/bindings.cpp, python_bindings/tests/bindings_test_filter.py
Expose filtering functionality introduced in #402 in Python API. Changes are kept to a minimum, only HNSW index is implemented and not brute force.
For a discussion of the interface design see [here](https://github.com/nmslib/hnswlib/pull/402#issuecomment-1250134730).
| filter | queries per second |
| ----------- | ----------- |
| 0.1 | 4241.43 |
| 0.2 | 5993.89 |
| 0.3 | 8232.54 |
| 0.4 | 10688.06 |
| 0.5 | 11677.54 |
| 0.6 | 13242.56 |
| 0.7 | 14520.50 |
| 0.8 | 14659.25 |
| 0.9 | 14932.67 |
| none | 503578.34 |
Here _filter_ denotes the fraction of elements the query was restricted to. _none_ denotes that no filtering has been applied.
As per the above table, there is a threshold below which exact ANN is probably preferable.
=> Python: filter elements with an optional filtering function

.github/workflows/build.yml, .gitignore, CMakeLists.txt, README.md, examples/multiThreadLoad_test.cpp, examples/multiThread_replace_test.cpp, hnswlib/bruteforce.h, hnswlib/hnswalg.h, hnswlib/hnswlib.h, python_bindings/bindings.cpp, python_bindings/tests/bindings_test_filter.py, python_bindings/tests/bindings_test_labels.py, python_bindings/tests/bindings_test_recall.py, python_bindings/tests/bindings_test_replace.py, python_bindings/tests/bindings_test_stress_mt_replace.py
Added a new method to replace a deleted element when a new one is added:
`labeltype addPointToVacantPlace(const void* data_point, labeltype label)`
The method is the same as `addPoint` but allows to replace a deleted element with a new one to save memory. Note: addPointToVacantPlace is much slower than addPoint, because replacement is a heavy operation.
Edit:
- Added replace a deleted element when a new one is added
- Fix of https://github.com/nmslib/hnswlib/issues/420 by introducing locks by label
- Added a multi thread test to test against concurrent operations with the same labels
- Added timeout to test jobs in actions in case if we have deadlock
- Refactoring
=> Replace deleted elements at addition

hnswlib/hnswalg.h
These getters are useful for resizing of the index from outside when the element count reaches capacity.
=> Getters for max elements, element count and num deleted.

hnswlib/hnswalg.h
Very similar in nature to https://github.com/nmslib/hnswlib/pull/344
I've discussed this fix with @dyashuni before and this has been tested on a number of datasets.
=> Fix insufficient results during filtering

.github/workflows/build.yml, README.md, examples/EXAMPLES.md, examples/example_filter.py, python_bindings/bindings.cpp, tests/python/bindings_test_filter.py
Add warning that python filter works slow in multi-threaded mode
Edit:
- added comments with warnings in examples
- added examples to CI test
=> Add code comments that python filter works slow in multi-threaded mode

ALGO_PARAMS.md, README.md
Hi there, here's a tiny PR to fix some typos in the HNSW params' docs :slightly_smiling_face:
=> chore(ALGO_PARAMS.md): Fix typo

hnswlib/hnswalg.h
Fix for #438. I have confirmed this removes the warning when building using R's C++ mingw tools.
=> #438: fix reordering warning

CMakeLists.txt
Add CMake install targets to allow installing the library using CMake and allow usage with find_package().
Other changes:
- Raise the minimum CMake version to 3.0. Testing CMake 2.8.12.2 on CentOS 7 generated errors already before doing these changes.
- Make the CMake project() name consistent with the library name (change `hnsw_lib` to `hnswlib`).
- Add option `HNSWLIB_EXAMPLES` to allow enabling/disabling tests and examples explicitly. Option defaults to previous behavior checking `CMAKE_PROJECT_NAME STREQUAL PROJECT_NAME`
=> Add CMake install targets

python_bindings/bindings.cpp, python_bindings/tests/bindings_test_bf_index.py
In some large scale applications BF index is slow therefore I added multithread search:
- added multi-threaded search for BF index
- added test to check BF index recall 
- added getters, setters for BF index in python
=> Add multithread search to BF index

hnswlib/hnswlib.h
This pull request solves the problem caused by BaseFilterFunctor not having a virtual destructor.
Example code:
```cpp
#include <iostream>
#include "hnswlib/hnswlib.h"
class CustomFilterFunctor : public hnswlib::BaseFilterFunctor {
public:
CustomFilterFunctor() {
std::cout << "constructor called" << std::endl;
}
bool operator()(hnswlib::labeltype id) {
return id % 2 == 0;
}
~CustomFilterFunctor() {
std::cout << "destructor called" << std::endl;
}
};
int main(int argc, char* argv[]) {
hnswlib::BaseFilterFunctor* filter = new CustomFilterFunctor();
delete filter;
return 0;
}
```
Compiling with `-Wall` option, a warning message about the lack of a virtual destructor is output:
```sh
$ g++ -Wall -std=c++11 example.cpp
example.cpp:19:3: warning: delete called on non-final …
```
=> Add virtual destructor to BaseFilterFunctor

hnswlib/bruteforce.h
It's more concise and more importantly forwards args so that the pair can be constructed in-place, instead of being created at the call-site and moved into push. It's not a big deal as both values are primitive types, but still...
=> Replace priority_queue::push with emplace.

tests/cpp/sift_1b.cpp, tests/cpp/updates_test.cpp
`sprintf` is deprecated and not secure, since it doesn't protect against buffer overflows. Also, string literals are `const char*`, not `char*`.
=> Fix build warnings.

hnswlib/bruteforce.h
Previous implementation was not thread-safe - unlike `addPoint` it didn't acquire an index lock.
While at it, this change also switches to `.find()` for cur_c lookups, so that following `erase` wouldn't have to perform another lookup.
P.S.: I don't see how `addPoint` is thread-safe as well, since write to data_ is performed outside of critical section, but oh well...
=> [bruteforce] Fix bruteforce removePoint.

hnswlib/bruteforce.h, hnswlib/hnswalg.h
Using raw pointers is error-prone. For example, previous implementation would leak pool in case it's created and loadIndex is invoked.
=> Use unique_ptr to manage visited_list_pool_

hnswlib/space_ip.h
InnerProductSIMD16ExtAVX512 functions are implemented using the more efficient AVX512 instruction set
=> Efficient AVX512  implementation in 'InnerProductSIMD16ExtAVX512' Function

hnswlib/hnswalg.h
This patch works around issue #467, also referenced as CVE-2023-37365, by implementing Yury Malkov's suggestion about capping the M value, coding the maximum number of outgoing connections in the graph, to a reasonable enough value of the order of 100000.  For the record, the documentation indicates reasonable values for M range from 2 to 100, which are well within the cap; see ALGO_PARAMS.md.
The reproducer shown in issue #467 doesn't trigger the double free condition anymore after this change is applied, but completes successfully, although with the below warning popping up on purpose:
warning: M parameter exceeds 100000 which may lead to adverse effects.
Cap to 100000 will be applied for the rest of the processing.
=> hnswalg.h: cap M to 100000

README.md, python_bindings/bindings.cpp, tests/python/bindings_test_getdata.py, tests/python/bindings_test_replace.py
Add `return_type `to `get_items`
Fixes https://github.com/nmslib/hnswlib/issues/223
=> Fix get_items

setup.py
Brining back `HNSWLIB_NO_NATIVE` to fix issue https://github.com/nmslib/hnswlib/pull/476
=> Bring back HNSWLIB_NO_NATIVE

hnswlib/hnswlib.h
Fixes linking error when compiling with Visual Studio and including hnswlib.h in more than one cpp file.
before:
2>Tools.lib(Pch.obj) : error LNK2005: "void __cdecl cpuid(int * const,int,int)" (?cpuid@@YAXQEAHHH@Z) already defined in Pch.obj 2>Tools.lib(NearestNeighbors.obj) : error LNK2005: "void __cdecl cpuid(int * const,int,int)" (?cpuid@@YAXQEAHHH@Z) already defined in Pch.obj 2>C:\Users\Rade\Documents\Data Analysis\Code\GenomicsLab Repo\x64\Release\ExpressionDemo.exe : fatal error LNK1169: one or more multiply defined symbols found 2>Done building project "ExpressionDemo.vcxproj" -- FAILED.
after:
2>ExpressionDemo.vcxproj -> C:\Users\Rade\Documents\Data Analysis\Code\GenomicsLab Repo\x64\Release\ExpressionDemo.exe
=> Linking error fix

hnswlib/hnswalg.h, hnswlib/hnswlib.h
#484 introduced a call to `std::cerr` when `M` is excessively large. This makes life hard for the [R bindings](https://github.com/jlmelville/rcpphnsw) because CRAN checks for and does not like to find anything writing to stdout/stderr (these streams should be sent to the console instead). Fortunately, the Rcpp library provides alternative streams (e.g. `Rcpp::Rcout` and `Rcpp::Rcerr`).
I propose using a macro to define the stream. By default this will be `std::cerr`, so users of this library need do nothing and will notice no changes. In RcppHNSW, I will create a header file which will declare the override, e.g.:
```C++
#include <Rcpp.h>
#define HNSWLIB_ERR_OVERRIDE Rcpp::Rcerr
#include "hnswlib.h"
```
A similar arrangement works for …
=> Provide a macro to override the use of std::cerr

hnswlib/hnswalg.h
GCC is complaining about different signedness in the loop which populates the return value in `getDataByLabel`:
```g++
warning: comparison of integer expressions of different signedness: ‘int’ and ‘size_t’ {aka ‘long unsigned int’} [-Wsign-compare]
795 |         for (int i = 0; i < dim; i++) {
```
The simplest fix, given here, is to change the type of the loop index `i` to `size_t`. A more idiomatic C++ approach would be to avoid introducing the loop in the first place, e.g.
```C++
std::copy(data_ptr, data_ptr + dim, std::back_inserter(data));
```
I checked that this worked (at least via the R bindings) but admittedly made no effort to do a proper performance check, so simpler is probably better.
=> Avoid sign mismatch in loop

hnswlib/hnswalg.h
GNU compilers no longer warn with -Wall or -Wreorder that initialisation order does not match declaration order in HierarchicalHNSW
=> Resolve initialisation order warning

hnswlib/bruteforce.h, python_bindings/bindings.cpp
There is a bug in the `searchKnn` function of `BruteforceSearch`. When it is used with a filter, in some cases, it returns fewer items than expected. This PR should fix it.
The bug can be reproduced using the following code:
```python
import hnswlib
data = [[0], [1], [2]]
max_elements = len(data)
dim = len(data[0])
bf_index = hnswlib.BFIndex(space='l2', dim=dim)
bf_index.init_index(max_elements=max_elements)
bf_index.add_items(data, ids=range(max_elements))
filter_function = lambda id: id in [0, 2]
labels, _ = bf_index.knn_query(data[0], k=2, filter=filter_function)
print(labels)
```
=> Fix incorrect results in bruteforce with filter

hnswlib/hnswalg.h
std::streampos position is never used.
=> remove unused variable
